/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HomeLayoutRouteImport } from './routes/_homeLayout'
import { Route as AboutLayoutRouteImport } from './routes/_aboutLayout'
import { Route as UserRouteRouteImport } from './routes/user/route'
import { Route as UserIndexRouteImport } from './routes/user/index'
import { Route as HomeLayoutIndexRouteImport } from './routes/_homeLayout/index'
import { Route as UserNameRouteImport } from './routes/user/$name'
import { Route as AboutLayoutAboutRouteImport } from './routes/_aboutLayout/about'

const HomeLayoutRoute = HomeLayoutRouteImport.update({
  id: '/_homeLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutLayoutRoute = AboutLayoutRouteImport.update({
  id: '/_aboutLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const UserRouteRoute = UserRouteRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => rootRouteImport,
} as any)
const UserIndexRoute = UserIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UserRouteRoute,
} as any)
const HomeLayoutIndexRoute = HomeLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HomeLayoutRoute,
} as any)
const UserNameRoute = UserNameRouteImport.update({
  id: '/$name',
  path: '/$name',
  getParentRoute: () => UserRouteRoute,
} as any)
const AboutLayoutAboutRoute = AboutLayoutAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AboutLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/user': typeof UserRouteRouteWithChildren
  '/about': typeof AboutLayoutAboutRoute
  '/user/$name': typeof UserNameRoute
  '/': typeof HomeLayoutIndexRoute
  '/user/': typeof UserIndexRoute
}
export interface FileRoutesByTo {
  '/about': typeof AboutLayoutAboutRoute
  '/user/$name': typeof UserNameRoute
  '/': typeof HomeLayoutIndexRoute
  '/user': typeof UserIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/user': typeof UserRouteRouteWithChildren
  '/_aboutLayout': typeof AboutLayoutRouteWithChildren
  '/_homeLayout': typeof HomeLayoutRouteWithChildren
  '/_aboutLayout/about': typeof AboutLayoutAboutRoute
  '/user/$name': typeof UserNameRoute
  '/_homeLayout/': typeof HomeLayoutIndexRoute
  '/user/': typeof UserIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/user' | '/about' | '/user/$name' | '/' | '/user/'
  fileRoutesByTo: FileRoutesByTo
  to: '/about' | '/user/$name' | '/' | '/user'
  id:
    | '__root__'
    | '/user'
    | '/_aboutLayout'
    | '/_homeLayout'
    | '/_aboutLayout/about'
    | '/user/$name'
    | '/_homeLayout/'
    | '/user/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  UserRouteRoute: typeof UserRouteRouteWithChildren
  AboutLayoutRoute: typeof AboutLayoutRouteWithChildren
  HomeLayoutRoute: typeof HomeLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_homeLayout': {
      id: '/_homeLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof HomeLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_aboutLayout': {
      id: '/_aboutLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AboutLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user': {
      id: '/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof UserRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/': {
      id: '/user/'
      path: '/'
      fullPath: '/user/'
      preLoaderRoute: typeof UserIndexRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/_homeLayout/': {
      id: '/_homeLayout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof HomeLayoutIndexRouteImport
      parentRoute: typeof HomeLayoutRoute
    }
    '/user/$name': {
      id: '/user/$name'
      path: '/$name'
      fullPath: '/user/$name'
      preLoaderRoute: typeof UserNameRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/_aboutLayout/about': {
      id: '/_aboutLayout/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLayoutAboutRouteImport
      parentRoute: typeof AboutLayoutRoute
    }
  }
}

interface UserRouteRouteChildren {
  UserNameRoute: typeof UserNameRoute
  UserIndexRoute: typeof UserIndexRoute
}

const UserRouteRouteChildren: UserRouteRouteChildren = {
  UserNameRoute: UserNameRoute,
  UserIndexRoute: UserIndexRoute,
}

const UserRouteRouteWithChildren = UserRouteRoute._addFileChildren(
  UserRouteRouteChildren,
)

interface AboutLayoutRouteChildren {
  AboutLayoutAboutRoute: typeof AboutLayoutAboutRoute
}

const AboutLayoutRouteChildren: AboutLayoutRouteChildren = {
  AboutLayoutAboutRoute: AboutLayoutAboutRoute,
}

const AboutLayoutRouteWithChildren = AboutLayoutRoute._addFileChildren(
  AboutLayoutRouteChildren,
)

interface HomeLayoutRouteChildren {
  HomeLayoutIndexRoute: typeof HomeLayoutIndexRoute
}

const HomeLayoutRouteChildren: HomeLayoutRouteChildren = {
  HomeLayoutIndexRoute: HomeLayoutIndexRoute,
}

const HomeLayoutRouteWithChildren = HomeLayoutRoute._addFileChildren(
  HomeLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  UserRouteRoute: UserRouteRouteWithChildren,
  AboutLayoutRoute: AboutLayoutRouteWithChildren,
  HomeLayoutRoute: HomeLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
